---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Effects of species life history and data availability on integrated population model performance


Abby E. Bratt, Caroline D. Cappello, Amelia J. DuVall, Hannah A. Sipe, Amanda J.
Warlick, Beth Gardner, Sarah J. Converse


## Abstract

Integrated population models (IPMs) can reduce bias, improve precision, and estimate parameters that would otherwise be unidentifiable and are therefore an increasingly popular tool for population modeling in ecology. However, the conditions under which IPMs yield these benefits is an active area of research. We simulated data across a range of life history strategies, population trajectories, and survey effort scenarios typical of a passerine monitoring program and examined model performance when count, mark-resight, and productivity datasets were included versus when datasets were omitted or were of poorer quality. In addition to parameter estimates having greater bias and lower precision when datasets directly informing those parameters were omitted, our results showed poorer vital rate estimation in scenarios where data were generated for a slow life history strategy and a decreasing abundance trend. In terms of abundance trend estimation, increasing count survey detection probability was more effective at reducing uncertainty in population growth rates than including additional datasets or having a longer monitoring period. This work informs the ongoing exploration of the benefits of IPMs and suggests that practitioners consider the context of a given species and monitoring program when determining whether investing in multiple datasets versus improving the quality of a single dataset will yield sufficiently precise parameter estimates that most efficiently answer pertinent ecological or management questions of interest.


## Scripts, current version

### 1 - preparing scenarios

##### generate_scenarios.R

Function 'getNviable' for finding the combinations of parameters that give a population growth rate ($\lambda$) within certain bounds, using the eigenvalue from the Leslie matrix. The output from this function produces the parameter scenarios used to simulate population trajectories, observation data from the trajectories, and fit the the IPM models. 

### 2 - models

##### IPM_marray.R
Script contains 4 IPM NIMBLE models. 

 1. full IPM model ('IPMmod') where all three datasets are included
 2. model without productivity dataset ('nonests')
 3. model without survival model ('nomr')
 4. abundance only model without productivity or survival ('abundonly')

### 3 - run models

##### run_scenarios_helperFns.R

Script with functions and code to run NIMBLE models. Function 'marray' transforms the survival data capture histories to m-array format. MCMC settings in this script, with functions for each of the 4 models. Each model has a run model function that defines constants, initial values, data, parameters to monitor, and code to build/run the models in NIMBLE. 

##### run_scenarios.R

Main workhorse script that simulates data and pulls from the scripts above to run models in parallel and output results. 

### 4 - process results

##### 01_load_and_process_data.R

Script that checks the Gelman-Rubin convergence statistic for each output MCMC sample, then thins the chains to reduce file size and places the output into categories based on the population growth rate, $\lambda$. 

##### 02_compute_geom_means.R

Computes the geometric means for $\lambda$ in each MCMC output. 

## Data

Contains demographic scenarios (combinations of abundance trend and life history traits) and survey scenarios (data availability and detection levels). 






